# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.example.com:587
mail_admin: mason@bonsai.so
mail_hostname: example.com
mail_user: smtp_user
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml

letsencrypt_contact_emails:
- "{{ mail_admin }}" # defined in groups_vars/all/mail.yml