# Created by trellis-cli v1.13.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  bonsai.so:
    site_hosts:
    - canonical: bonsai.test
      redirects:
      - www.bonsai.test
    local_path: ../site
    admin_email: admin@bonsai.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
